### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by Carson-Ray** [qtgiebel/portfolio#2]
# Design/Code Review 1

### Reviewer: Carson Roedl

|Item |Considerations| Comments/Suggestions|
|--------|---------|---|
|||Reviewer comments and suggestions go here. Each item should have *at least* one "kudos" and two suggestions for improvement|
|**Problem Statement**|1. Accurately describes project purpose<br> 2. Is professional and free of typos, slang, etc.<br> 3. Fully explains the problem and the solution<br> 4. Is understandable by the average person| Great problem statement, explains the project well. Fully explains the project. Could add user stories for non admin/day-to-day users (only slightly applicable to this specific project, so disregard if not useful) |
|**Design Documentation**|1. Navigation/flow through the application is logical and easy to use. <br>2. The order in which values are displayed are logical and easy to understand/use <br>3. The order in which the form fields entered are logical and easy to understand/use<br>4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens | Design is well though out and comprehensive. The flow is good between pages, and will be easier to see once deployed and working on the web. Not currently using forms. All data appears to be represented on the screens. |
|**Data model/Database**|1. Everything on the screens and problem statement/flow is represented in the model <br> 2. There is at least one 1-to-many relationship.<br> 3. The model represents good database design <br>| Database is put together well and has diagrams detailing the data being stored. It might be possible to split up the permissions from the user table, but not necessary. Everything displayed on the screen does depict what is represented in the models. |
|**Code**|1. Proper Maven project structure is used<br> 2. a .gitignore file for IntelliJ Java projects has been implemented <br> 3. There is not any redundant or copy/paste code in the JSPs or classes<br> 4. Classes are appropriately-sized (no monster classes)<br> Property files are used appropriately: no hard-coded values <br> 5. Logging statements are used rather than System.out.println and printStackTrace.<br> 6. There are appropriate unit tests/code coverage.  | Code is neat and well written, proper files have been included (gitignore, pom, etc.). Could include some more javadocs (will be added over time, unless not wanting to jdoc variables). JSP files look good, and just need some basic styling to look great when deployed. |

**Comment by pawaitemadisoncollege** [comment]
Be sure to swap in logging statements for these or throw the exception up to the caller... https://github.com/qtgiebel/portfolio/search?q=print
